(source melpa)

(depends-on "magit")
(depends-on "auto-complete")
(depends-on "helm")
(depends-on "undo-tree")
(depends-on "expand-region")
(depends-on "multiple-cursors")
(depends-on "rainbow-delimiters")
(depends-on "flycheck")
(depends-on "anzu")
(depends-on "volatile-highlights")
(depends-on "sequential-command")
(depends-on "powerline")
(depends-on "smartrep")
